### ISSUE TITLE
Gem::ConflictError

### ISSUE THREAD

**Issue by orenyomtov** [erwanlr/Fingerprinter#22]
Hi,

I'm receiving the following error when trying to run the tool:

```
$ ./fingerprinter.rb
/Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate cms_scanner-0.0.37.9, because nokogiri-1.8.0 conflicts with nokogiri (~> 1.7.1), activesupport-5.1.3 conflicts with activesupport (~> 5.0.1) (Gem::ConflictError)
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:220:in `rescue in try_activate'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:213:in `try_activate'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
  from /Users/user/Research/Fingerprinter/lib/fingerprinter/actions.rb:6:in `<top (required)>'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
  from /Users/user/Research/Fingerprinter/lib/fingerprinter.rb:8:in `<top (required)>'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/user/Research/Fingerprinter/lib/fingerprinters.rb:7:in `<top (required)>'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/user/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from ./fingerprinter.rb:6:in `<main>'
```

Any ideas on how to resolve this conflict?

**Comment by erwanlr** [comment]
I had this one some time ago, tried to fix it but couldn't do it properly and was in a rush.

What worked was to manually remove the versions causing the conflicts (with gem uninstall), so in your case, nokogiri 1.8.0 and activesupport 5.1.3. This is dirty, I know ;p

I will have another look when possible to try to solve that.
