### ISSUE TITLE
Latest build - run error 

### ISSUE THREAD

**Issue by Os3r3um** [erwanlr/Fingerprinter#30]
Hi there, 

I do get this error message while trying to run it:  

CLI: ./fingerprinter.rb  --app-name  wordpress --fingerprint "http://target.com/"

```
invalid byte sequence in US-ASCII
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/rule.rb:126:in `count'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/rule.rb:126:in `initialize'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/rule.rb:117:in `new'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/rule.rb:117:in `build'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/rule.rb:332:in `factory'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/list.rb:93:in `block (2 levels) in parse'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/list.rb:75:in `each_line'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/list.rb:75:in `block in parse'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/list.rb:107:in `initialize'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/list.rb:74:in `new'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/list.rb:74:in `parse'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix/list.rb:49:in `default'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.0/lib/public_suffix.rb:122:in `valid?'
/var/lib/gems/2.3.0/gems/cms_scanner-0.0.38.4/lib/cms_scanner/target/scope.rb:52:in `<<'
/var/lib/gems/2.3.0/gems/cms_scanner-0.0.38.4/lib/cms_scanner/target.rb:18:in `initialize'
/mnt/cici/attack_platform/cms/Fingerprinter/lib/cli_options.rb:87:in `new'
/mnt/cici/attack_platform/cms/Fingerprinter/lib/cli_options.rb:87:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/2.3.0/optparse.rb:1547:in `block in parse_in_order'
/usr/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
/usr/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
/usr/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
/usr/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
/usr/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
/mnt/cici/attack_platform/cms/Fingerprinter/lib/cli_options.rb:103:in `<top (required)>'
./fingerprinter.rb:11:in `require'
./fingerprinter.rb:11:in `<main>'
```

Any ideas about what might cause this crash?

Thanks!

**Comment by erwanlr** [comment]
Seems like you have a non UTF-8 character in the target url, could you please send it to team at wpscan dot org please ?

**Comment by Os3r3um** [comment]
Okay. Thanks!
